// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmA-z8VHtsmyBpQSjHI2D6fzul2UyxsxQ',
    appId: '1:138443301310:web:2eff93b6c4091d5ec0d9ef',
    messagingSenderId: '138443301310',
    projectId: 'legalplatformmaster',
    authDomain: 'legalplatformmaster.firebaseapp.com',
    storageBucket: 'legalplatformmaster.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-AGXe8fB8jYMMfV6Av2vUNFy1tiUAxU',
    appId: '1:138443301310:android:97d18fcebb75fc20c0d9ef',
    messagingSenderId: '138443301310',
    projectId: 'legalplatformmaster',
    storageBucket: 'legalplatformmaster.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpO6y27HqPiMMFizh1EW6P1KelMC0isDg',
    appId: '1:138443301310:ios:2a4661dabe3932f9c0d9ef',
    messagingSenderId: '138443301310',
    projectId: 'legalplatformmaster',
    storageBucket: 'legalplatformmaster.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
